[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-template"
version = "0.1.0"
authors = [
    { name = "Nagesh Bansal", email = "nagesh@findme.com" }
]
description = "FastAPI Template Application"
requires-python = ">=3.8"
